MYNOTEBOOKS = [
    "Examples/Alignment",
    "Examples/Automata",
    "Examples/GraphColoring",
    "Examples/MultitargetRNADesign",
    "Examples/NetworkParsimony",
    "Tutorials/Bookchapter",
    "Tutorials/RNA Design"
  ]

GENERATED_FILES=[
	"Examples/dependency_graph.dot",
	"Examples/dependency_graph.pdf",
	"Examples/dependency_graph.png",
	"Examples/f3_-5_hist.svg",
	"Examples/f3_-5_logo.svg",
	"Examples/f3_0_hist.svg",
	"Examples/f3_0_logo.svg",
	"Examples/hardwired-network",
	"Examples/hardwired-network.pdf",
	"Examples/input-network",
	"Examples/input-network.pdf",
	"Examples/parental-network",
	"Examples/parental-network.pdf",
	"Examples/softwired-network",
	"Examples/softwired-network.pdf",
	"Examples/tmp_out.png",
	"Examples/treedecomp.pdf",
	"Examples/treedecomp.png",
	"Tutorials/count_matrix.pdf",
	"Tutorials/dependency_graph.dot",
	"Tutorials/dependency_graph.pdf",
	"Tutorials/dependency_graph.png",
	"Tutorials/gc_content_minus-logo.svg",
	"Tutorials/gc_content_plus-logo.svg",
	"Tutorials/gc_content_zero-logo.svg",
	"Tutorials/optimization.svg",
	"Tutorials/test.svg",
	"Tutorials/tmp_out.png",
	"Tutorials/treedecomp.dot",
	"Tutorials/treedecomp.pdf",
	"Tutorials/treedecomp.png"
]


TARGETS = expand("{nb}.{ext}", nb=MYNOTEBOOKS, ext=["md"])

rule all:
    input:
        TARGETS
    output:
        "html/index.html"
    shell:
        "cd ..; doxygen src/doxygen.cfg"

rule convert_py_to_ipynb:
    input:
        "{notebook}.py"
    output:
        "{notebook}.ipynb"
    shell:
        "jupytext --to notebook --execute '{input}'"


rule convert_ipynb_to_markdown:
    input:
        "{notebook}.ipynb"
    output:
        "{notebook}.md"
    shell:
        "jupyter nbconvert --to markdown '{input}'"

rule clean:
    run:
        import os
        import shutil
        for f in GENERATED_FILES:
            if os.path.exists(f):
                os.remove(f)

rule realclean:
    run:
        import os
        import shutil
        for f in TARGETS+GENERATED_FILES:
            if os.path.exists(f):
                os.remove(f)
           
        for f in MYNOTEBOOKS:
            dir = f"{f}_files"
            if os.path.exists(dir):
                shutil.rmtree(dir)
